<?php
/**
 * SPANISH language file: please UTF-8 encoding only, so use UTF-8 compliant editor only
 ****************************************************************************************/

$GLOBALS['L'] = array (
    'Forums Index' => 'Índice del Foro',
    'Forums' => 'Foros',
    'Forum' => 'Foro',
    'Topics' => 'Temas',
    'Topic' => 'Tema',
    'Orca Forum' => ':: Foro',
    'Logged in as' => 'Logueado como',
    'Manage Forum' => 'Administrar Foro',
    'Reported Posts' => 'Entradas Reportadas',
    'Logout' => 'Salir',
    'My Flags' => 'Mis Suscripciones',
    'Flag' => 'Subscribirse',
    'Unflag' => 'Eliminar Suscripción',
    'My Topics' => 'Mis Temas',
    'Login' => 'Ingresar',
    'Search' => 'Buscar',
    'Copyright' => 'Derechos Reservados',
    'New Group' => 'Nuevo Grupo',
    'New Topic' => 'Nuevo Tema',
    'Post Reply' => 'Responder',
    'Lock' => 'Bloquear',
    'Unlock' => 'Desbloquear',
    'Stick' => 'Resaltar',
    'Unstick' => 'Eliminar Resaltado',
    'Author' => 'Autor',
    'Message' => 'Mensaje',
    'posts:' => 'entradas:',
    'Delete' => 'Borrar',
    'Edit' => 'Editar',
    'Quote' => 'Cita',
    'post is hidden' => 'entrada oculta',
    'hide post' => 'ocultar entrada',
    'show post' => 'mostrar entrada',
    'Points:' => 'Puntos:',
    'Vote' => 'Votar',
    'Access denied' => 'Acceso denegado. Debes tener permisos para acceder a esta área.',
    'New topic created' => 'Se ha creado un nuevo tema',
    'return to forum index' => 'regresar al índice del foro',
    'Edit group' => 'Editar grupo',
    'New group' => 'Nuevo grupo',
    'Cancel' => 'Cancelar',
    'Submit' => 'Enviar',
    'Submit' => 'Enviar',
    'New forum' => 'Nuevo Foro',
    'Forum title:' => 'Título del Foro:',
    'Forum description:' => 'Descripción del Foro:',
    'Forum type:' => 'Tipo de Foro:',
    'public' => 'público',
    'private' => 'privado',
    'Latest Reply' => 'Última Respuesta',
    'Latest Post' => 'Última Entrada',
    'Posts' => 'Entradas',
    'Pages:' => 'Páginas:',
    'Join' => 'Ingresar',
    'Forums Spy' => 'Spías de los Foros <span>(una visión de la actividad en tiempo real)</span>',
    'said in' => 'dijo en',
    'Topic subject:' => 'Contenido del Tema:',
    'Topic subject Error' => 'Por favor ingresa entre 5 y 50 símbolos',
    'Topic forum Error' => 'Por favor selecciona un foro para añadir un tema',
    'Select Forum' => 'Seleccionar Foro',
    'Sticky' => 'Resaltado',
    'Topic text:' => 'Texto del Tema:',
    'Topic text Error' => 'Por favor ingresa entre 5 y 128000 símbolos',
    'Post Reply:' => 'Publicar Respuesta:',
    'Special Member' => 'Miembro Especial',
    'Standard Member' => 'Miembro Estándar',
    'Member Info' => 'Información del Miembro',
    'Joined:' => 'Registrado:',
    'Last Online:' => 'Último Online:',
    'Posts:' => 'Entradas:',
    'Last Post:' => 'Última Entrada:',
    'never' => 'nunca',
    'Find all posts by' => 'Hallar todas las entradas por',
    'New Search' => 'Nueva Búsqueda',
    'Search Results For:' => 'Buscar Resultados por:',
    'There are no search results.' => 'No hay resultados para esta búsqueda.',
    'Please try search again.' => 'Por favor <a href="javascript:void(0);" onclick="return f.showSearch()" >intenta de nuevo</a>.',
    'Date' => 'Fecha',
    'Search The Forum' => 'Buscar en el Foro',
    'Search for:' => 'Buscar por:',
    'Where to Search:' => 'Dónde buscar:',
    'Topic Titles' => 'Títulos de Temas',
    'Messages' => 'Mensajes',
    'Forum:' => 'Foro:',
    'Whole Forum' => 'Todo el Foro',
    'Author:' => 'Autor:',
    'Display:' => 'Mostrar:',

    'Site is unavailable' => 'Lo sentimos, algo ha salido mal y el sitio no se encuentra disponible, por favor intenta más tarde.',
    'Join Login Username Error' => 'Nombre de usuario debe tener entre 4 y 12 caracteres',
    'Join Email Error' => 'El Email debe ser válido',
    'Username must be uniq' => 'El Email debe ser único',
    'Login Password Error' => 'El Password debe ser válido',
    'Email must be uniq' => 'El Email debe ser único',
    'Database error' => 'Error de Base de Datos',
    'Send mail failed' => 'Falló el envío del correo',
    'password or login is incorrect' => 'usuario o password incorrecto',
    'Cookies must be enabled to process login' => 'Los Cookies deben estar habilitado para poder ingresar',

    'Username' => 'Usuario',
    'Password' => 'Password',
    'Email' => 'Email',
    'Wrong search type' => 'Tipo de búsqueda errónea',
    'Topics you participate in' => 'Temas en los que participas',
    'Flagged topics' => 'Suscripciones a Temas',
    'Topics you have flagged' => 'Temas a los que te has suscrito',
    '%s\'s forum posts' => 'Temas de foro de %s',
    'Forum Posts' => 'Entradas de Foro',
    'Minute Ago' => 'Minuto antes',
    'Minutes Ago' => 'Minutos antes',
    'Hour Ago' => 'Hora antes',
    'Hours Ago' => 'Horas antes',
    'Day Ago' => 'Día antes',
    'Days Ago' => 'Días antes',
    'Mail Subj Registration' => 'Detalles de Registro del Foro',
    'Mail Body Registration' => "
<p>Dear {username},</p>

<p>
Tu usuario: {username} <br />
Tu Password: {pwd} <br />
URL del sitio: {site_url} <br />
</p>

<p>
Gracias por registrarte.
</p>
<p>
Los mejores deseos, El Foro.
</p>
",
    'xml serialization failed' => 'falló la serialización xml',
    'please upgrade your browser' => 'por favor actualiza tu navegador',
    'XML read failed:' => 'falló la lectura XML:',
    'There was a problem retrieving the XML data:' => 'Hubo un problema recuperando los datos XML:',
    'httpxml object creation failed' => 'falló la creación del objeto httpxml',

    'LOADING LOGIN FORM' => 'CARGANDO FORMULARIO DE INGRESO',
    'LOADING JOIN FORM' => 'CARGANDO FORMULARIO DE REGISTRO',
    'SEARCHING' => 'BUSCANDO',
    'LOADING FORUMS' => 'CARGANDO FOROS',
    'LOADING FORUM TOPICS' => 'CARGANDO TEMAS DEL FORO',
    'LOADING FORUM INDEX' => 'CARGANDO ÍNDICE DEL FORO',
    'LOADING PROFILE PAGE' => 'CARGANDO PÁGINA DE PERFIL',
    'LOADING TOPIC POSTS' => 'CARGANDO ENTRADAS DE TEMAS',
    'LOADING POST TOPIC PAGE' => 'CARGANDO PÁGINA DE TEMAS DE ENTRADAS',
    'LOADING' => 'CARGANDO',
    'LOADING SEARCH PAGE' => 'CARGANDO PÁGINA DE BÚSQUEDA',
    'LOADING POST REPLY PAGE' => 'CARGANDO PÁGINA DE RESPUESTA DE ENTRADAS',
    'SENDING MESSAGE' => 'ENVIANDO MENSAJE',
    'POST IS LOADING' => 'ENTRADA CARGÁNDOSE',

    'Thank you! You Joined! Your login and password have been sent to your email.' => '¡Muchas gracias! ¡Te has registrado! Tu usuario y password han sido enviados a tu correo.',
    'Join failed' => 'Falló el registro',
    'Login failed' => 'Falló el ingreso',
    'orca_main div is not defined' => 'No está definido el div orca_main',
    'please name orca_main content container' => 'por favor coloca un nombre al contenedor orca_main',
    'category id is not defined' => 'El ID de la categoría no está definido',
    'please set category ids' => 'Por favor inserta los IDs de categorías',
    'Please login to view topics you participate in' => 'Por favor ingresar para ver los temas en los que has participado',
    'Please login to view flagged topics' => 'Por favor ingresa para ver las suscripciones a temas',
    'Are you sure ?' => '¿Estás seguro?',
    'Post was successfully deleted' => 'La entrada ha sido borrado correctamente',
    'Topic and post were successfully deleted' => 'El tema y la entrada fueron borrados correctamente',
    'Post was successfully edited' => 'Entrada editada correctamente',
    'Message body empty' => 'Cuerpo del Mensaje vacío',
    'Valid chars:' => 'Chars válidos:',
    'Topic has been successfully added to your flagged topics' => 'Te has suscrito al tema correctamente',
    'Topic has been successfully removed from your flagged topics' => 'El tema ha sido removido de tus suscripciones correctamente',
    'Please login to flag topics' => 'Por favor ingresa para suscribirte al tema',
    'Post has been reported' => 'El tema ha sido reportado',
    'Report error' => 'Report error',
    'add this to title' => ' :: Foro ',
    'Are you sure to delete category with all forums, topics and post?' => '¿Estás seguro de querer borrar la categoría con todos sus foros, temas y entradas?',
    'Category has been successfully deleted' => 'Categoría borrada correctamente',
    'Can not delete category' => 'No se puede borrar la categoría',
    'Are you sure to delete forum with topics and posts' => '¿Estás seguro de querer borrar el foro con todos sus temas y entradas?',
    'Forum has been successfully deleted' => 'El Foro ha sido borrado',
    'Can not delete forum' => 'No se puede borrar el foro',
    'Group has been successfully modified' => 'El Grupo ha sido modificado',
    'New group has been successfully added' => 'Se ha añadido el Nuevo Grupo',
    'Can not modify group' => 'No se puede modificar el grupo',
    'Can not add new group' => 'No se puede añadir el nuevo grupo',
    'Forum has been successfully modified' => 'El Foro ha sido modificado',
    'New forum has been successfully added' => 'Se ha añadido el Nuevo Foro',
    'Can not modify forum' => 'No se puede modificar el foro',
    'Can not add new forum' => 'No se puede añadir el nuevo foro',
    'Topic has been successfully locked' => 'El tema ha sido bloqueado',
    'Topic has been successfully unlocked' => 'El tema ha sido desbloqueado',
    'Topic has been successfully sticked' => 'El tema ha sido resaltado',
    'Topic has been successfully un-sticked' => 'Se ha eliminado el resaltado del Tema',
    'Only admin can lock/unlock topics' => 'Sólo el administrador puede bloquear/desbloquear temas',
    'new group' => 'nuevo grupo',
    'edit' => 'editar',
    'delete' => 'borrar',
    'new forum' => 'nuevo foro',
    'permalink' => 'permalink',
    'report this post' => 'reportar esta entrada',
    'Compile Langs' => 'Compilar Idiomas',
    'Compile Lang:' => 'Compilar Idioma:',
    'Language files compilation have been failed' => 'La compilación de archivos de idioma ha fallado. Por favor chequea los permisos de las carpetas.',
    'Language files have been successfully compiled' => 'Los archivos de idioma han sido compilados correctamente',
    'Permalink' => 'Permalink',
    'RSS feed' => 'Feed RSS',
    'RSS Feed' => 'Feed RSS',
    'No topics' => 'No hay temas en este foro',
    '# forums' => '# foros',
    '# topics' => '# temas',
    '# posts' => '# entradas',
    '# points' => '# mascotas como ésta',
    'last update: #' => 'última actualización: #',
    'last reply by # %' => 'última respuesta por # %',
    'last reply by #' => 'última respuesta por #',
    'created by # %' => 'creado por # %',
    'Report' => 'Reportar',
    'Forum order:' => 'Orden del foro:',
    'Group name:' => 'Nombre de grupo:',
    'Group order:' => 'Orden de Grupo:',
    'Expand group by default:' => 'Expandir grupo por defecto:',
    'Clear report' => 'Limpiar reporte',
    'Topic has been successfully hidden' => 'El Tema ha sido ocultado',
    'Topic has been successfully un-hidden' => 'El Tema ya no está oculto',
    'Hidden Topics' => 'Temas ocultos',
    'Hidden Posts' => 'Entradas ocultas',
    'Move topic form' => 'Mover formulario de tema',
    'Move Topic' => 'Mover Tema',
    'Unhide Topic' => 'Mostrar Tema',
    'Hide Topic' => 'Esconder Tema',
    'Delete Topic' => 'Borrar Tema',
    'Forum to move topic to:' => 'Foro al cual mover el Tema:',
    'After moving go to:' => 'Después de mover ir a:',
    'Stay here' => 'Quedarse aquí',
    'Forum where topic is moved' => 'Foro al cual se movió el tema',
    'Allowed edit post period is elapsed' => 'El período permitido para editar la entrada ha terminado',
    'Allowed edit post period is # seconds' => 'El período permitido para editar el post es # segundos',
    'Recent Topics' => 'Temas Recientes',
    'No posts' => 'No hay entradas recientes',
    'Attach one more file' => 'Adjuntar otro archivo',
    'Attachments:' => 'Adjuntos:',
    'Some or all files upload failed' => 'Falló la carga de uno o tods los archivos',
    '# downloads' => '# descargas',
    '# views' => '# vistas',
    'Hide' => 'Esconder',
    'Unhide' => 'Mostrar',
    'Change Signature' => 'Cambiar Firma',
    'Signature text Error' => 'El máximo es 100 caracteres',
    'Updated Topics' => 'Temas Actualizados',
    'Like' => 'Votar',
    'Bury' => 'Esconder',
    'Edit forum' => 'Editar foro',
    'continue_topic_suffix - %d' => ' - parte %d',
    'continue_topic_last %s' => '<div class="forum_robot_msg bx-def-font">%s &#8594;</div>',
    'continue_topic_first %s' => '<div class="forum_robot_msg bx-def-font">&#8592; %s</div>',
    'insert to post' => 'insertar en la entrada',
);

?>
